# Generated by Django 4.0.5 on 2022-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alerta_checkbox_alerta_precocompra_alerta_precovenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='precocompra',
            new_name='compra',
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='precovenda',
            new_name='venda',
        ),
    ]
