# Generated by Django 4.0.5 on 2022-06-16 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alerta_duracao_alerta_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='checkbox',
            new_name='aceito',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='duracao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
