# Generated by Django 4.0.5 on 2022-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_alerta_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='email',
            field=models.EmailField(default='alertas@stockwatch.com', max_length=254),
        ),
    ]
