# Generated by Django 4.0.5 on 2022-06-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_alerta_ativo_alerta_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='ativo',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ativo',
            field=models.ManyToManyField(to='mainapp.ativo'),
        ),
    ]
