# Generated by Django 4.0.5 on 2022-06-18 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0026_remove_ativo_user_alerta_aceito_remove_alerta_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='aceito',
        ),
        migrations.AddField(
            model_name='ativo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='ativo',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ativo',
            field=models.ManyToManyField(to='mainapp.ativo'),
        ),
    ]
