# Generated by Django 4.0.5 on 2022-06-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0028_remove_alerta_ativo_alerta_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraAtivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Carteira 01', max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('quantidade', models.IntegerField(default=0)),
                ('tenho', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remuneracao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nota', models.IntegerField(default=0)),
                ('v_investido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('v_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rentabilidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ativo')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nota'],
            },
        ),
    ]
