# Generated by Django 4.0.5 on 2022-06-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_carteiraativo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteiraativo',
            name='rentabilidade',
        ),
        migrations.RemoveField(
            model_name='carteiraativo',
            name='v_final',
        ),
        migrations.RemoveField(
            model_name='carteiraativo',
            name='v_investido',
        ),
    ]
