# Generated by Django 4.0.5 on 2022-06-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_remove_carteiraativo_rentabilidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteiraativo',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='carteiraativo',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='carteiraativo',
            name='tenho',
        ),
    ]
