# Generated by Django 4.0.5 on 2022-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alerta_mercado_delete_alarmibovespa_alerta_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='precocompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='alerta',
            name='precovenda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
