# Generated by Django 4.0.5 on 2022-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_precocompra_alerta_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='duracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='periodo',
            field=models.IntegerField(default=30),
        ),
    ]
