# Generated by Django 4.0.5 on 2022-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_checkbox_alerta_aceito_alter_alerta_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='duracao',
            field=models.IntegerField(default=30),
        ),
    ]
