# Generated by Django 4.0.5 on 2022-06-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alerta_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='duracao',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='email',
            field=models.EmailField(default='me@preencha.pvr', max_length=254),
        ),
    ]
