# Generated by Django 4.0.5 on 2022-06-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_alerta_duracao_alter_alerta_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='email',
            field=models.EmailField(default='fill@me.plz', max_length=254),
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mercado')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.AlterField(
            model_name='alerta',
            name='ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ativo'),
        ),
    ]
