# Generated by Django 4.0.5 on 2022-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_alerta_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='ativo',
            field=models.CharField(default='itsa4', max_length=10),
        ),
    ]
