# Generated by Django 4.0.5 on 2022-06-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alerta_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='itsa4', max_length=30)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mercado')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
