# Generated by Django 4.0.5 on 2022-06-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ativo'),
        ),
    ]
