# Generated by Django 4.0.5 on 2022-06-18 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0020_alter_alerta_aceito'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
