# Generated by Django 4.0.5 on 2022-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_ativo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='aceito',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='email',
            field=models.EmailField(default='deveria.ser@email.registrado', max_length=254),
        ),
    ]
