# Generated by Django 4.0.5 on 2022-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_alerta_aceito_alter_alerta_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='ativo',
        ),
        migrations.AddField(
            model_name='alerta',
            name='ativo',
            field=models.ManyToManyField(to='mainapp.ativo'),
        ),
    ]
