# Generated by Django 4.0.5 on 2022-06-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_rename_carteiraativos_carteiraativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteiraativo',
            name='name',
        ),
    ]
